module.exports = {
  STATUS_CODES: {
    ACCESS_DENIED: 401,
    BAD_REQUEST: 400,
    OK: 200,
    INTERNAL_ERROR: 500,
    NOT_FOUND: 404,
  },
  VERIFY_EMAIL: "VERIFY_EMAIL",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  FEEDBACK_CREATED:"FEEDBACK_CREATED",
  ACTIVE: "Active",
  SUSPENDED: "Suspended",
  SUCCESS_MESSAGES: {
    BANNER_CREATED:"Banner Created Successfully",
    BANNER_FETCHED:"Banner Fetched Successfully",
    CATEGORY_DELETED:"Category Deleted Successfully",
    CATEGORY_UPDATED:"Category Updated Successfully",
    CATEGORY_CREATED:"Category Created Successfully",
    CATEGORY_SERVICE_ITEM_CREATED:"Category Service Item Created Successfully",
    CATEGORY_SHOP_SERVICE_CREATED:"Category Shop Service Created Successfully",
    CATEGORY_SHOP_CREATED:"Category Shop Created Successfully",
    CATEGORY_SHOP_SERVICE_ITEM_CREATED:"Category Shop Service Item Created Successfully",
    OTP_SENT_LOGIN:"OTP Send SuccessFully For Login",
    OTP_SENT_SIGNUP:"OTP Send SuccessFully For SignUp",
    PREFERENCES_UPDATED:"Notification Days Saved Successfully",
    OTP_SEND: "Successfully sent OTP to email.",
    EMAIL_VERIFIED: "Email Verified Successfully",
    OTP_VERIFIED: "OTP Verified Successfully",
    PROFILE_UPDATE: "Profile updated successfully",
    PASSWORD_UPDATE: "Password updated successfully.",
    REQUEST_SENT_TO_ADMIN: "Request sent successfully to admin.",
    SUCCESS_UPDATE: "Updated successfully",
    USER_UPDATED: "User updated successfully",
    USER_DELETED: "User deleted successfully",
    USER_FETCH: "Users fetched successfully",
    USER_REGISTRATION: "User registered successfully.",
    USER_LOGIN: "User logged in successfully.",
    USER_LOGOUT: "User logged out successfully",
    PRODUCT_CREATION: "Product created successfully.",
    PRODUCT_DETAILS: "Product details fetched successfully.",
    PRODUCTS_FETCHED: "Products fetched successfully",
    CATEGORIES_FETCHED: "Categories fetched successfully",
    CATEGORIES_SHOP_FETCHED:"Category Shop fetched successfully",
    CATEGORIES_SHOP_SERVICE_FETCHED:"Category Shop fetched successfully",
    FAQ_FETCHED: "FAQ fetched successfully",
    ADS_FETCHED: "Ads fetched successfully",
    PASSWORD_UPDATED: "Password Updated Successfully",
    PRODUCT_DELETED: "Product deleted successfully",
    FEEDBACK_CREATED: 'Feedback submitted successfully',
    FEEDBACKS_FETCHED: 'Feedbacks retrieved successfully',
    REMINDER_ADDED: 'Reminder added successfully.'
  },
  ERROR_MESSAGES: {
    NO_BANNER_FOUND:"No Banner Found",
    CATEGORY_NOT_FOUND:"Category Not Found",
    INVALID_DAYS:"invalid days",
    NEW_EMAIL_REQUIRED:"New email required",
    CLIENT_ERROR: "Something went wrong",
    UNAUTHORIZED: "Unauthorized access",
    EMAIL_EXIST: "Email already exists.",
    CONTACT_NUMBER_NOT_FOUND: "Contact Number does not exist.",
    INVAILD_OTP: "Invalid OTP.",
    PASSWORD_INVALID: "Invalid Email and Password.",
    PHONE_EXIST: "Phone number already exists.",
    PLAYER_NOT_FOUND: "Player does not exist",
    PHONE_NOT_FOUND: "Phone number does not exist.",
    PASSWORD_NOT_MATCH: "New password and confirm password do not match.",
    USER_NOT_FOUND: "User does not exist",
    USER_NAME_EXIST: "user name already exists.",
    PRODUCT_NOT_FOUND: "Product details not found",
    NO_PRODUCTS_FOUND: "Products not found",
    NO_CATEGORIES_FOUND: "Categories not found",
    NO_FAQ_FOUND: "Faq not found",
    NO_ADS_FOUND: "Ads not found",
    INCORRECT_OLD_PASSWORD: "Invalid Password",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    NO_CATEGORIES_FOUND:"No Categories Found",
    PRODUCT_NOT_FOUND: 'Product not found.',
    INVALID_CATEGORY_ID:"Invalid category id",
    FILENOTDELETED:"File not deleted",
    INTERNAL_SERVER_ERROR: 'An error occurred while processing your request. Please try again later.'
   },
 };
